"""Read-only evidence gates, including deliberately broken inputs. No SPICE."""
import json
from pathlib import Path
import pytest
from nebula import submission_evidence as E
from nebula.submission_preflight import check_run

def test_exact_selected_receiver_and_nonmatching_circuit(tmp_path):
    result=E.receiver_for(E.SAVED_ROOT/E.FINAL_RUN)
    assert result['correct_bits']==result['scored_bits']==64
    assert result['full_receiver_verified'] is False
    assert result['signed_model_domain_pass'] is False
    assert result['aperture_above_100mv_ui']==pytest.approx(.675)
    (tmp_path/'design.cir').write_text('unrelated circuit')
    assert E.receiver_for(tmp_path) is None

@pytest.mark.parametrize('name',['../outside','missing','C:/Windows/test','..\\outside'])
def test_preflight_rejects_unsafe_or_missing_file(tmp_path,name):
    with pytest.raises(ValueError): E.checked_file(tmp_path,name,'0'*64)

def test_hash_mismatch_is_a_failure(tmp_path):
    (tmp_path/'design.cir').write_text('changed')
    with pytest.raises(ValueError,match='hash mismatch'): E.checked_file(tmp_path,'design.cir','0'*64)

def test_receiver_unrecorded_path_refused():
    with pytest.raises(ValueError):E.receiver_artifact('../independent_review.json')

def test_saved_preflight_and_ownership():
    result=check_run()
    assert result['status']=='PASS' and result['simulations_launched']==0
    index=E.evidence_index(E.SAVED_ROOT/E.FINAL_RUN,E.FINAL_RUN)
    assert len({row['circuit'] for row in index['rows']})==3
    assert all(len(row['sha256'])==64 for row in index['rows'])

def test_incomplete_receipt_fails(tmp_path):
    (tmp_path/'run').mkdir()
    (tmp_path/'run/workflow_receipt.json').write_text(json.dumps({'output_complete':False}))
    with pytest.raises(ValueError,match='accepted complete'):check_run(tmp_path,'run')

def test_no_judge_mode_and_scope_labels():
    static=Path('nebula/web/static')
    html=(static/'index.html').read_text(encoding='utf-8')
    js=(static/'app.js').read_text(encoding='utf-8')
    assert all(s not in html+js for s in ('judgeButton','judgeStrip','enterJudgeMode','exitJudgeMode','data-judge-target'))
    assert 'Saved replay; originally generated by live pipeline' in js
    assert '+/- 1.5 dB' in js and '+/- 0.3 octave' in js
    assert 'loading="eager"' in html
